version: '3.1'
services:
  dbpostgresql:
    container_name: dbpostgresql
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
  searcher-api:
    container_name: searcher-api
    image: searcher-api
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  web:
    container_name: searcher
    image: searcher
    restart: on-failure
    ports:
      - "4200:80"
    depends_on:
      - searcher-api
